//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Waste_Bin_Collections.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFullExtract
    {
        public string KEYVAL { get; set; }
        public string UPRN { get; set; }
        public Nullable<decimal> SAO_START_NO { get; set; }
        public string SAO_START_SFX { get; set; }
        public Nullable<decimal> SAO_END_NO { get; set; }
        public string SAO_END_SFX { get; set; }
        public string SAO_DESC { get; set; }
        public string SAON { get; set; }
        public Nullable<decimal> PAO_START_NO { get; set; }
        public string PAO_START_SFX { get; set; }
        public Nullable<decimal> PAO_END_NO { get; set; }
        public string PAO_END_SFX { get; set; }
        public string PAO_DESC { get; set; }
        public string PAON { get; set; }
        public string STREET_NAME { get; set; }
        public string LOCALITY_NAME { get; set; }
        public string POSTAL_TOWN { get; set; }
        public string POSTCODE { get; set; }
        public string MAP_EAST { get; set; }
        public string MAP_NORTH { get; set; }
        public string Primary { get; set; }
        public string Secondary { get; set; }
        public string Tertiary { get; set; }
        public string ORGANISATION { get; set; }
        public string BLPU_LOGICAL_STATUS { get; set; }
        public string BLPU_STATE { get; set; }
        public string LPI_LOGICAL_STATUS { get; set; }
        public string REL_POS_ACC { get; set; }
        public System.DateTime BLPU_Created_Date { get; set; }
        public System.DateTime BLPU_Updated_Date { get; set; }
        public System.DateTime LPI_Created_Date { get; set; }
        public System.DateTime LPI_Updated_Date { get; set; }
    }
}
